# Generated by Django 2.2.16 on 2022-09-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_category_comment_genre_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
