# Generated by Django 2.2.16 on 2022-09-28 21:58

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220928_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=reviews.models.get_current_year, message='Произведение еще не вышло!')]),
        ),
    ]
