# Generated by Django 2.2.16 on 2022-09-29 19:32

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220928_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.username_validator], verbose_name='Имя пользователя'),
        ),
    ]
